# Generated by Django 3.2.8 on 2021-10-21 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=400, unique=True, verbose_name='Lien boutique')),
                ('name', models.CharField(max_length=255, verbose_name='Nom boutique')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Description court')),
                ('category', models.CharField(max_length=255, verbose_name='Catégorie')),
                ('city', models.CharField(max_length=150, verbose_name='Ville')),
                ('picture', models.URLField(blank=True, max_length=400, null=True, verbose_name='Logo')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('web_site', models.URLField(blank=True, max_length=400, null=True, verbose_name='Site web')),
                ('long_description', models.TextField(blank=True, null=True, verbose_name='Description longue')),
                ('added_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Boutique',
                'verbose_name_plural': 'Boutiques',
                'ordering': ('added_date',),
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=400, unique=True, verbose_name='Lien produit')),
                ('title', models.CharField(max_length=255, verbose_name='Titre produit')),
                ('category', models.CharField(max_length=255, verbose_name='Catégorie produit')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Prix produit')),
                ('image_1', models.URLField(blank=True, max_length=400, null=True, verbose_name='Produit image 1')),
                ('image_2', models.URLField(blank=True, max_length=400, null=True, verbose_name='Produit image 2')),
                ('image_3', models.URLField(blank=True, max_length=400, null=True, verbose_name='Produit image 3')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description produit')),
                ('date_published', models.DateField(verbose_name='Date publication')),
                ('boutique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boutique', to='avito.boutique', verbose_name='Boutique')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ('date_published',),
            },
        ),
    ]
