# Generated by Django 3.2.8 on 2021-10-25 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Particulier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom utilisateur')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('city', models.CharField(max_length=150, verbose_name='Ville')),
                ('added_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Particulier',
                'verbose_name_plural': 'Particuliers',
                'ordering': ('added_date',),
            },
        ),
        migrations.CreateModel(
            name='ParticulierProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=400, unique=True, verbose_name='Lien produit')),
                ('title', models.CharField(max_length=255, verbose_name='Titre annonce')),
                ('category', models.CharField(max_length=255, verbose_name='Catégorie annonce')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Prix annonce')),
                ('image_1', models.URLField(blank=True, max_length=400, null=True, verbose_name='Annonce image 1')),
                ('image_2', models.URLField(blank=True, max_length=400, null=True, verbose_name='Annonce image 2')),
                ('image_3', models.URLField(blank=True, max_length=400, null=True, verbose_name='Annonce image 3')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description annonce')),
                ('date_published', models.DateField(verbose_name='Date publication')),
                ('particulier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Particulier', to='avito.particulier', verbose_name='Particulier')),
            ],
            options={
                'verbose_name': 'Particulier annonce',
                'verbose_name_plural': 'Particulier annonces',
                'ordering': ('date_published',),
            },
        ),
    ]
