# Generated by Django 3.2.8 on 2021-10-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito', '0002_particulier_particulierproduit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particulier',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Téléphone'),
        ),
    ]
