# Generated by Django 3.2.8 on 2021-10-26 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito', '0003_alter_particulier_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particulierproduit',
            name='url',
            field=models.URLField(max_length=400, verbose_name='Lien produit'),
        ),
        migrations.AlterUniqueTogether(
            name='particulierproduit',
            unique_together={('particulier', 'url')},
        ),
    ]
