# Generated by Django 3.2.8 on 2021-10-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensooq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opensooqboutique',
            options={'ordering': ('added_date',), 'verbose_name': '0 - OpenSooq Boutique', 'verbose_name_plural': '0 - OpenSooq Boutiques'},
        ),
        migrations.AlterModelOptions(
            name='opensooqboutiqueproduit',
            options={'ordering': ('date_published',), 'verbose_name': '0 - OpenSooq Produit', 'verbose_name_plural': '0 - OpenSooq Produits'},
        ),
        migrations.AlterField(
            model_name='opensooqboutique',
            name='picture',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='opensooqboutique',
            name='url',
            field=models.URLField(max_length=1000, unique=True, verbose_name='Lien boutique'),
        ),
        migrations.AlterField(
            model_name='opensooqboutiqueproduit',
            name='image_1',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Produit image 1'),
        ),
        migrations.AlterField(
            model_name='opensooqboutiqueproduit',
            name='image_2',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Produit image 2'),
        ),
        migrations.AlterField(
            model_name='opensooqboutiqueproduit',
            name='image_3',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Produit image 3'),
        ),
        migrations.AlterField(
            model_name='opensooqboutiqueproduit',
            name='url',
            field=models.URLField(max_length=1000, verbose_name='Lien produit'),
        ),
    ]
