# Generated by Django 3.2.8 on 2021-10-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensooq', '0002_auto_20211027_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opensooqboutique',
            name='url',
            field=models.URLField(max_length=2000, unique=True, verbose_name='Lien boutique'),
        ),
        migrations.AlterField(
            model_name='opensooqboutiqueproduit',
            name='url',
            field=models.URLField(max_length=2000, verbose_name='Lien produit'),
        ),
    ]
