# Generated by Django 3.2.8 on 2021-10-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensooq', '0003_auto_20211027_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opensooqboutique',
            name='picture',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='opensooqboutiqueproduit',
            name='image_1',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Produit image 1'),
        ),
        migrations.AlterField(
            model_name='opensooqboutiqueproduit',
            name='image_2',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Produit image 2'),
        ),
        migrations.AlterField(
            model_name='opensooqboutiqueproduit',
            name='image_3',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='Produit image 3'),
        ),
    ]
