# Generated by Django 3.2.8 on 2021-10-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensooq', '0004_auto_20211027_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opensooqboutiqueproduit',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Prix produit'),
        ),
    ]
