# Generated by Django 3.2.8 on 2021-10-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opensooq', '0006_auto_20211028_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opensooqparticulierproduit',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Prix annonce'),
        ),
    ]
