# Generated by Django 3.2.8 on 2021-10-29 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Olx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom utilisateur')),
                ('city', models.CharField(max_length=150, verbose_name='Ville')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Téléphone')),
                ('added_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '0 - Olx Particulier',
                'verbose_name_plural': '0 - Olx Particuliers',
                'ordering': ('added_date',),
            },
        ),
        migrations.CreateModel(
            name='OlxProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000, verbose_name='Lien produit')),
                ('title', models.CharField(max_length=255, verbose_name='Titre annonce')),
                ('category', models.CharField(max_length=255, verbose_name='Catégorie annonce')),
                ('price', models.FloatField(default=0.0, verbose_name='Prix annonce')),
                ('image_1', models.URLField(blank=True, max_length=2000, null=True, verbose_name='Annonce image 1')),
                ('image_2', models.URLField(blank=True, max_length=2000, null=True, verbose_name='Annonce image 2')),
                ('image_3', models.URLField(blank=True, max_length=2000, null=True, verbose_name='Annonce image 3')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description annonce')),
                ('date_published', models.DateField(verbose_name='Date publication')),
                ('particulier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olx', to='olx.olx', verbose_name='Particulier')),
            ],
            options={
                'verbose_name': '0 - Olx produit',
                'verbose_name_plural': '0 - Olx produits',
                'ordering': ('date_published',),
                'unique_together': {('particulier', 'url')},
            },
        ),
    ]
