# Generated by Django 3.2.9 on 2021-11-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jiji', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiji',
            name='country',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Country'),
        ),
    ]
